# Generated by Django 4.0.5 on 2022-06-11 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('average_dmg', models.PositiveIntegerField(null=True, verbose_name='Average Damage')),
            ],
            options={
                'verbose_name': 'Attack',
                'verbose_name_plural': 'Attacks',
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start time')),
            ],
            options={
                'verbose_name': 'Battle',
                'verbose_name_plural': 'Battles',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hp', models.PositiveIntegerField(null=True, verbose_name='Current Hit Points')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Damage Type',
                'verbose_name_plural': 'damage types',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Race',
                'verbose_name_plural': 'Races',
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('attack_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skyrim_app.attack')),
            ],
            options={
                'verbose_name': 'Spell',
                'verbose_name_plural': 'Spells',
            },
            bases=('skyrim_app.attack',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time of the Event')),
                ('damage', models.PositiveIntegerField(null=True, verbose_name='Damage Inflicted')),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss_attack', related_query_name='%(class)ss_in_attack', to='skyrim_app.character', verbose_name='Attacker')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)ss_in', to='skyrim_app.battle')),
                ('damaged', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss_damage', related_query_name='%(class)s', to='skyrim_app.character', verbose_name='Damaged in Event')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', related_query_name='%(class)ss_with', to='skyrim_app.race', verbose_name='Race'),
        ),
        migrations.AddField(
            model_name='character',
            name='weakness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', related_query_name='%(class)ss_with_weakness', to='skyrim_app.damagetype', verbose_name='Weakness'),
        ),
        migrations.AddField(
            model_name='battle',
            name='participants',
            field=models.ManyToManyField(related_name='%(class)ss', related_query_name='%(class)ss_in', to='skyrim_app.character', verbose_name='Battle Participants'),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss_win', related_query_name='%(class)ss_won', to='skyrim_app.character', verbose_name='Winner'),
        ),
        migrations.AddField(
            model_name='attack',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', related_query_name='%(class)ss_with', to='skyrim_app.damagetype', verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skyrim_app.character')),
                ('spell_slot1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss_1', related_query_name='%(class)ss_in_slot1', to='skyrim_app.spell', verbose_name='Spell in use in Slot 1')),
                ('spell_slot2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss_2', related_query_name='%(class)ss_in_slot2', to='skyrim_app.spell', verbose_name='Spell in use in Slot 2')),
                ('spell_slot3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss_3', related_query_name='%(class)ss_in_slot3', to='skyrim_app.spell', verbose_name='Spell in use in Slot 3')),
                ('spells_known', models.ManyToManyField(related_name='%(class)ss', related_query_name='%(class)ss_with', to='skyrim_app.spell', verbose_name='Spells Known')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
            bases=('skyrim_app.character',),
        ),
        migrations.CreateModel(
            name='Beast',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skyrim_app.character')),
                ('attacks', models.ManyToManyField(related_name='%(class)ss', related_query_name='%(class)ss_with', to='skyrim_app.attack', verbose_name='Attacks')),
            ],
            options={
                'verbose_name': 'Beast',
                'verbose_name_plural': 'Beasts',
            },
            bases=('skyrim_app.character',),
        ),
    ]
