# Generated by Django 4.0.4 on 2022-06-09 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avg_damage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('life_points', models.PositiveIntegerField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skyrim_app.breed')),
            ],
        ),
        migrations.CreateModel(
            name='DateAndTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_damage', models.CharField(choices=[('Fire', 'Fire'), ('Frost', 'Frost'), ('Poison', 'Poison'), ('Shock', 'Shock')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Beast',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skyrim_app.character')),
            ],
            bases=('skyrim_app.character',),
        ),
        migrations.CreateModel(
            name='BeastAttack',
            fields=[
                ('attack_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skyrim_app.attack')),
            ],
            bases=('skyrim_app.attack',),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skyrim_app.character')),
            ],
            bases=('skyrim_app.character',),
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('attack_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skyrim_app.attack')),
            ],
            bases=('skyrim_app.attack',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_number', models.PositiveIntegerField()),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='skyrim_app.attack')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='skyrim_app.battle')),
                ('character_atack', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='skyrim_app.character')),
                ('character_receive_atack', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='skyrim_app.character')),
                ('date_time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='skyrim_app.dateandtime')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='weakness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyrim_app.typeofdamage'),
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='skyrim_app.battle')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skyrim_app.character')),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='battle_winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='skyrim_app.character'),
        ),
        migrations.AddField(
            model_name='battle',
            name='date_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='skyrim_app.dateandtime'),
        ),
        migrations.AddField(
            model_name='attack',
            name='type_of_damage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skyrim_app.typeofdamage'),
        ),
        migrations.CreateModel(
            name='PlayerKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='skyrim_app.player')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='skyrim_app.spell')),
            ],
        ),
        migrations.CreateModel(
            name='InUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='skyrim_app.player')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='skyrim_app.spell')),
            ],
        ),
        migrations.CreateModel(
            name='BeastKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='skyrim_app.beastattack')),
                ('beast', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='skyrim_app.beast')),
            ],
        ),
    ]
