# Generated by Django 4.0.5 on 2022-06-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrim_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='average_dmg',
            field=models.PositiveIntegerField(verbose_name='Average Damage'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hp',
            field=models.PositiveIntegerField(verbose_name='Current Hit Points'),
        ),
        migrations.AlterField(
            model_name='event',
            name='damage',
            field=models.PositiveIntegerField(verbose_name='Damage Inflicted'),
        ),
    ]
