# Generated by Django 4.0.5 on 2022-06-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrim_app', '0003_alter_beast_attacks_alter_character_weakness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beast',
            name='attacks',
            field=models.ManyToManyField(related_name='%(class)ss', related_query_name='%(class)ss_with', to='skyrim_app.attack', verbose_name='Attacks'),
        ),
        migrations.AlterField(
            model_name='player',
            name='spells_known',
            field=models.ManyToManyField(related_name='%(class)ss', related_query_name='%(class)ss_with', to='skyrim_app.spell', verbose_name='Spells Known'),
        ),
    ]
