# Generated by Django 4.0.5 on 2022-06-11 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyrim_app', '0004_alter_beast_attacks_alter_player_spells_known'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='weakness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', related_query_name='%(class)ss_with_weakness', to='skyrim_app.damagetype', verbose_name='Weakness'),
        ),
        migrations.AlterField(
            model_name='player',
            name='spell_slot1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss_1', related_query_name='%(class)ss_in_slot1', to='skyrim_app.spell', verbose_name='Spell in use in Slot 1'),
        ),
        migrations.AlterField(
            model_name='player',
            name='spell_slot2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss_2', related_query_name='%(class)ss_in_slot2', to='skyrim_app.spell', verbose_name='Spell in use in Slot 2'),
        ),
        migrations.AlterField(
            model_name='player',
            name='spell_slot3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss_3', related_query_name='%(class)ss_in_slot3', to='skyrim_app.spell', verbose_name='Spell in use in Slot 3'),
        ),
    ]
