# Generated by Django 4.0.5 on 2022-06-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrim_app', '0005_alter_character_weakness_alter_player_spell_slot1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beast',
            name='attacks',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', related_query_name='%(class)ss_with', to='skyrim_app.attack', verbose_name='Attacks'),
        ),
        migrations.AlterField(
            model_name='player',
            name='spells_known',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', related_query_name='%(class)ss_with', to='skyrim_app.spell', verbose_name='Spells Known'),
        ),
    ]
