# Generated by Django 4.0.5 on 2022-06-11 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyrim_app', '0006_alter_beast_attacks_alter_player_spells_known'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attack',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', related_query_name='%(class)ss_with', to='skyrim_app.attack', verbose_name='Attack'),
            preserve_default=False,
        ),
    ]
