# Generated by Django 4.0.5 on 2022-06-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyrim_app', '0007_event_attack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attack',
            options={'ordering': ['name'], 'verbose_name': 'Attack', 'verbose_name_plural': 'Attacks'},
        ),
        migrations.AlterModelOptions(
            name='battle',
            options={'get_latest_by': 'start', 'ordering': ['-start'], 'verbose_name': 'Battle', 'verbose_name_plural': 'Battles'},
        ),
        migrations.AlterModelOptions(
            name='beast',
            options={'ordering': ['name'], 'verbose_name': 'Beast', 'verbose_name_plural': 'Beasts'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='damagetype',
            options={'ordering': ['name'], 'verbose_name': 'Damage Type', 'verbose_name_plural': 'damage types'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'time', 'ordering': ['time'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name'], 'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['name'], 'verbose_name': 'Race', 'verbose_name_plural': 'Races'},
        ),
        migrations.AlterModelOptions(
            name='spell',
            options={'ordering': ['name'], 'verbose_name': 'Spell', 'verbose_name_plural': 'Spells'},
        ),
    ]
