# Generated by Django 4.0.5 on 2024-08-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrim_app', '0008_alter_attack_options_alter_battle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
