# Generated by Django 4.0.5 on 2024-08-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrim_app', '0009_alter_attack_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
